name: macOS with VNC

on: workflow_dispatch

jobs:
  vnc:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Grant execute permissions
        run: chmod +x ./configure.sh

      - name: Configure VNC and start pinggy
        # Run the script as root to set up VNC, user, and tunnel
        run: |
          sudo ./configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD" 
        env:
          VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
          VNC_PASSWORD:      ${{ secrets.VNC_PASSWORD }}

      - name: Keep runner alive
        # Prevent the job from exiting so the VM stays up for VNC
        run: while true; do sleep 3600; done
