name: macos-with-vnc
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setting the environment up.
      env:
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: source configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD" 

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
