name: macos-with-vnc
on: [workflow_dispatch]
jobs:
  build:
    # Use a macOS runner
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Enable VNC and start pinggy tunnel
        env:
          VNC_USER_PASSWORD: 2009
          VNC_PASSWORD: 2222
        run: |
          source ./configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD"

      - name: Output connection info
        run: |
          echo "Connect via VNC to the address above, using user 'vncuser' and password ${VNC_PASSWORD}."
      - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
