name: macos-with-vnc

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup and start VNC + Pinggy
        env:
          VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
          VNC_PASSWORD:      ${{ secrets.VNC_PASSWORD }}
        run: |
          # make sure the script is executable
          chmod +x configure.sh

          # Pass all three args: user-pw, vnc-pw, ngrok token
          ./configure.sh \
            "$VNC_USER_PASSWORD" \
            "$VNC_PASSWORD" \

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
