name: macos-with-vnc
on: [push]
jobs:
  vnc:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run setup script
      run: |
        sudo bash ./configure.sh

    - name: Start Pinggy TCP tunnel
      run: |
        # Use TCP tunnel (-R) for port 5900 (VNC). $PINGGY_TOKEN is a secret.
        ssh -p 443 -R0:localhost:5900 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 gtcxZbEfnfR+tcp@free.pinggy.io &
        echo "Pinggy VNC tunnel started; check the runner logs for the public URL."

    - name: Keep job alive
      run: sleep 3600
